bin/github_verify_committers.php

Add logging

---

bin/github_verify_committers.php

Define global valiables for logger

---

services/providers/github.php

Improve logging to better track transactions

---

services/providers/github.php

Remove email notification if state is a success

---

bin/github_verify_committers.php

Support for multiple GitHb repos for a project.  Instead of matching an eclipse project name to a GitHub repo name (where there can only be 1:1) we match repo names to project names.

Bug 462239: Support for multiple Github repos for one project

---

services/providers/github.php

Bug 462324: IP Validation fails but doesn't say why

---

bin/github_verify_committers.php

Bug 463796: [GitHub] Committer Sync: Eclipse group members flawed

---

lib/organization/eclipse.php
lib/organization/organization.php
services/providers/github.php

(fix regression causing status to be empty)

Bug 466480: PRs from committers not passing validation

---

lib/organization/eclipse.php

(regression with logger, improve status response)

Bug 466480: PRs from committers not passing validation 

---

bin/github_install_hooks.php
bin/github_verify_committers.php
config/projects.php
lib/json_store.php
lib/ldapclient.php
lib/logger.php
lib/mysql_store.php
lib/organization/eclipse.php
lib/organization/github.php
lib/organization/locationtech.php
lib/organization/organization.php
lib/organization/polarsys.php
lib/organization/team.php
lib/restclient.php
lib/status_store.php
services/cla_service.php
services/github_api_limit.php
services/github_service.php
services/providers/github.php
services/providers/stub.php
services/status_details.php
services/stub_service.php

Bug 466872: Locationtech web hook points to dev.eclipse.org, doesn't

---

config/projects.php
lib/organization/github.php
lib/restclient.php
services/providers/github.php
test/pagination.php

Bug 461914 - API calls to lists must deal with pagination

---

lib/restclient.php

Bug 466872 - Locationtech web hook points to dev.eclipse.org

---

services/providers/hooks/pull_request_opened.php.sample

Bug 462471: Github link to Bugzilla, bugzilla link to Github PR

---

lib/organization/eclipse.php
services/providers/github.php

Remove case-sensitivity on email checks

---

lib/organization/eclipse.php

Bug 469140 - [webhook] Prioritize Github user name instead of email

---

lib/restclient.php

Increase curl timeout to 60s (from 4s)

---

bin/github_get_issues.php
config/projects.php
lib/organization/github.php
lib/restclient.php
services/github_api_limit.php
services/providers/github.php

Bug 481771 - Support GitHub Issues

---

lib/ldapclient.php

Bug 489685: Pull request for Kura with CLA validation failing with no

---

lib/organization/eclipse.php

Signed-off-by: MWEclipse <matt.ward@eclipse.org>

Potential fix for bug 521596

---

bin/github_get_issues.php
bin/github_install_hooks.php
bin/github_verify_committers.php
lib/organization/eclipse.php
lib/organization/github.php
lib/organization/organization.php
lib/organization/team.php

Signed-off-by: Eclipse Webmaster <webmaster@eclipse.org>

Changes to work with multiple orgs

---

bin/github_verify_committers.php
lib/organization/github.php
lib/restclient.php

Signed-off-by: Eclipse Webmaster <webmaster@eclipse.org>

Code additions and changes to resolve bug 532093

---

lib/organization/eclipse.php
services/github_api_limit.php
services/github_service.php

Signed-off-by: Eclipse Webmaster <webmaster@eclipse.org>

Updates to use the defined endpoint among other things
